---
# Gitをインストール
- name        : Gitが依存するライブラリをインストール
  yum         :
    name      : "{{ item }}"
    state     : installed
  with_items  :
    - gettext-devel
    - expat-devel
    - curl-devel
    - zlib-devel
    - perl-devel
    - openssl-devel
    - subversion-perl
    - make
    - gcc

- name: インストールするGitのバージョンを取得
  command: >
    git --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: no
  register: git_installed_version

- name: インストールしたいバージョンとインストール済のバージョンが違った場合、強制的にGitをインストールする
  set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update
    - git_installed_version|success and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") | version_compare(git_version, operator="!="))

- name: Gitのソースコードをダウンロードする
  get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "{{ git_workspace }}/git-{{ git_version }}.tar.gz"
  when:  git_installed_version|failed or git_reinstall_from_source

- name: 解凍する
  unarchive:
    src: "{{ git_workspace }}/git-{{ git_version }}.tar.gz"
    dest: "{{ git_workspace }}"
    creates: "{{ git_workspace }}/git-{{ git_version }}/README"
    copy: no
  when:  git_installed_version|failed or git_reinstall_from_source

- name: Gitをビルドする
  command: >
    make prefix={{ git_install_path }} {{ item }}
    chdir={{ git_workspace }}/git-{{ git_version }}
  with_items:
    - all
    - install
  when:  git_installed_version|failed or git_reinstall_from_source
  become: yes
