---
# - name            : phpMyAdmin をダウンロード
#   get_url         :
#     url           : "{{ phpMyAdmin.url }}"
#     dest          : "{{ phpMyAdmin.work_dir }}"
#     validate_certs: no

# - name           : ダウンロードした phpMyAdmin ファイルを解凍
#   unarchive      :
#     src          : "{{ phpMyAdmin.work_dir }}/{{ phpMyAdmin.package_filename }}.tar.gz"
#     dest         : "{{ phpMyAdmin.deploy_dir}}"
#     owner        : root
#     group        : root
#     copy         : no
#     creates      : "{{ phpMyAdmin.home_dir }}"

# - name           : phpMyAdmin ディレクトリの配置
#   shell          : "mv {{ phpMyAdmin.deploy_dir }}/{{ phpMyAdmin.package_filename}} {{ phpMyAdmin.home_dir }}"
#   args:
#     creates      : "{{ phpMyAdmin.home_dir }}"

# - name           : phpMyAdmin の設定ファイルを配置
#   shell          : "cp -p {{ phpMyAdmin.home_dir }}/config{.sample,}.inc.php"
#   args           :
#     creates: "{{ phpMyAdmin.home_dir }}/config.inc.php"

# - name           : phpMyAdmin 設定ファイル編集
#   lineinfile     :
#     dest         : "{{ phpMyAdmin.home_dir }}/config.inc.php"
#     backrefs     : yes
#     regexp       : "{{ item.regexp }}"
#     line         : "{{ item.line }}"
#   with_items     : "{{ phpMyAdmin.config_changes }}"
#   notify         : httpd再起動
