---

- name          : mariadbをインストール
  yum           :
    name        : "{{ item }}"
    state       : installed
  with_items    :
    - MySQL-python
    - mariadb
    - mariadb-server
    - libselinux-python
    - libsemanage-python

- name          : Configure SELinux to start mysql on any port
  seboolean     :
    name        : mysql_connect_any
    state       : true
    persistent  : yes
  when          : ansible_selinux.status == "enabled"

- name          : mariadbを起動
  service:
    name        : mariadb
    state       : started
    enabled     : yes

- name                   : MySQLのrootユーザーを設定
  mysql_user             :
    name                 : root
    host                 : localhost
    password             : "{{ mysql_root_password }}"
    login_user           : root
    login_password       : "{{ mysql_root_password }}"
    check_implicit_admin : yes

- name          : my.cnf_baseをアップロード
  template      :
    src         : my.cnf_base
    dest        : /etc/my.cnf
  notify        : mariadb再起動

- name          : my.cnfをアップロード (ansibleでDB作成などできるようにするため)
  template      :
    src         : my.cnf
    dest        : /root/.my.cnf
    owner       : root
    mode        : 0600

- name          : データベースを作成
  mysql_db      :
    name        : "{{ db_name_first }}"
    state       : present

- name          : MySQLユーザーを作成
  mysql_user    :
    name        : "{{ mysql_user_first }}"
    host        : "{{ item }}"
    password    : "{{ mysql_password_first }}"
    priv        : "{{ db_name_first }}.*:ALL,GRANT"
    state       : present
  with_items    :
      - localhost
      - 192.168.10.%

# - name            : phpMyAdmin をダウンロード
#   get_url         :
#     url           : "{{ phpMyAdmin.url }}"
#     dest          : "{{ phpMyAdmin.work_dir }}"
#     validate_certs: no

# - name           : ダウンロードした phpMyAdmin ファイルを解凍
#   unarchive      :
#     src          : "{{ phpMyAdmin.work_dir }}/{{ phpMyAdmin.package_filename }}.tar.gz"
#     dest         : "{{ phpMyAdmin.deploy_dir}}"
#     owner        : root
#     group        : root
#     copy         : no
#     creates      : "{{ phpMyAdmin.home_dir }}"

# - name           : phpMyAdmin ディレクトリの配置
#   shell          : "mv {{ phpMyAdmin.deploy_dir }}/{{ phpMyAdmin.package_filename}} {{ phpMyAdmin.home_dir }}"
#   args:
#     creates      : "{{ phpMyAdmin.home_dir }}"

# - name           : phpMyAdmin の設定ファイルを配置
#   shell          : "cp -p {{ phpMyAdmin.home_dir }}/config{.sample,}.inc.php"
#   args           :
#     creates: "{{ phpMyAdmin.home_dir }}/config.inc.php"

# - name           : phpMyAdmin 設定ファイル編集
#   lineinfile     :
#     dest         : "{{ phpMyAdmin.home_dir }}/config.inc.php"
#     backrefs     : yes
#     regexp       : "{{ item.regexp }}"
#     line         : "{{ item.line }}"
#   with_items     : "{{ phpMyAdmin.config_changes }}"
#   notify         : httpd再起動
