---
# Apache
- name          : httpdインストール
  yum           :
    name        : httpd-{{ httpd_version }}
    state       : installed

- name          : httpd起動
  service       :
    name        : httpd
    state       : started
    enabled     : yes
  ignore_errors : true

# SSLに必要なものをインストール
- name          : mod_sslインストール
  yum           :
    name        : mod_ssl
    state       : installed

- name          : opensslインストール
  yum           :
    name        : openssl
    state       : installed

# SSL用の秘密鍵を生成
- name      : SSL用の秘密鍵を生成 local_dev
  command   : "openssl genrsa -out {{ ssl_key_local_dev }} 2048"
  args      :
    creates : "{{ ssl_key_local_dev }}"
  when      : target_is_local

- name      : SSL用の秘密鍵を生成 remote_staging
  command   : "openssl genrsa -out {{ ssl_key_remote_staging }} 2048"
  args      :
    creates : "{{ ssl_key_remote_staging }}"
  when      : target_is_remote

- name      : SSL用の秘密鍵を生成 remote_production
  command   : "openssl genrsa -out {{ ssl_key_remote_production }} 2048"
  args      :
    creates : "{{ ssl_key_remote_production }}"
  when      : target_is_remote

# SSLのCSRを生成
- name      : SSLのCSRを生成 local_dev
  command   : "openssl req -new -key {{ ssl_key_local_dev }} -out {{ ssl_csr_local_dev }} -subj '/C=JP/ST=Tokyo/L=Tokyo/O=ltd/OU=Web/CN=domain'"
  args      :
    creates : "{{ ssl_csr_local_dev }}"
  when      : target_is_local

- name      : SSLのCSRを生成 remote_staging
  command   : "openssl req -new -key {{ ssl_key_remote_staging }} -out {{ ssl_csr_remote_staging }} -subj '/C=JP/ST=Tokyo/L=Tokyo/O=ltd/OU=Web/CN=domain'"
  args      :
    creates : "{{ ssl_csr_remote_staging }}"
  when      : target_is_remote

- name      : SSLのCSRを生成 remote_production
  command   : "openssl req -new -key {{ ssl_key_remote_production }} -out {{ ssl_csr_remote_production }} -subj '/C=JP/ST=Tokyo/L=Tokyo/O=ltd/OU=Web/CN=domain'"
  args      :
    creates : "{{ ssl_csr_remote_production }}"
  when      : target_is_remote

# SSLの自己証明書を生成
- name      : SSLの自己証明書を生成 local_dev
  command   : "openssl x509 -in {{ ssl_csr_local_dev }} -days 3650 -req -signkey {{ ssl_key_local_dev }} -out {{ ssl_crt_local_dev }}"
  args      :
    creates : "{{ ssl_crt_local_dev }}"
  when      : target_is_local

- name      : SSLの自己証明書を生成 remote_staging
  command   : "openssl x509 -in {{ ssl_csr_remote_staging }} -days 3650 -req -signkey {{ ssl_key_remote_staging }} -out {{ ssl_crt_remote_staging }}"
  args      :
    creates : "{{ ssl_crt_remote_staging }}"
  when      : target_is_remote

- name      : SSLの自己証明書を生成 remote_production
  command   : "openssl x509 -in {{ ssl_csr_remote_production }} -days 3650 -req -signkey {{ ssl_key_remote_production }} -out {{ ssl_crt_remote_production }}"
  args      :
    creates : "{{ ssl_crt_remote_production }}"
  when      : target_is_remote

# VirtualHostの設定
- name        : VirtualHostを有効にする
  notify      : httpd再起動
  lineinfile  :
    dest      : /etc/httpd/conf/httpd.conf
    state     : present
    backrefs  : yes
    regexp    : '#NameVirtualHost \*:80'
    line      : 'NameVirtualHost *:80'

- name        : VirtualHostを有効にする(SSL)
  notify      : httpd再起動
  template    :
    src       : ssl.conf.j2
    dest      : /etc/httpd/conf.d/ssl.conf

- name        : 仮想マシンにVirtualHostの設定ファイルを作成
  notify      : httpd再起動
  template    :
    src       : local_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_local

- name        : 本番サーバーにVirtualHostの設定ファイルを作成
  notify      : httpd再起動
  template    :
    src       : remote_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_remote
