---
# Apache
- name          : httpdインストール
  yum           :
    name        : httpd-{{ httpd_version }}
    state       : installed

- name          : httpd起動
  service       :
    name        : httpd
    state       : started
    enabled     : yes

# DocumentRootを書き換え
- name        : /etc/httpd/conf/httpd.confを書き換え
  lineinfile  :
    dest      : /etc/httpd/conf/httpd.conf
    state     : present
    backrefs  : yes
    regexp    : '#NameVirtualHost \*:80'
    line      : 'NameVirtualHost *:80'

- name        : 仮想マシンに/etc/httpd/conf.d/virtualhost.confファイルを作成
  notify      : httpd再起動
  template    :
    src       : local_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_local

- name        : 本番サーバーに/etc/httpd/conf.d/virtualhost.confファイルを作成
  notify      : httpd再起動
  template    :
    src       : remote_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_remote
