---
# Apache
- name          : httpdインストール
  yum           :
    name        : httpd-{{ httpd_version }}
    state       : installed

- name          : httpd起動
  service       :
    name        : httpd
    state       : started
    enabled     : yes

# SSL
- name          : mod_sslインストール
  yum           :
    name        : mod_ssl
    state       : installed

- name          : opensslインストール
  yum           :
    name        : openssl
    state       : installed

# VirtualHostの設定
- name        : VirtualHostを有効にする
  notify      : httpd再起動
  lineinfile  :
    dest      : /etc/httpd/conf/httpd.conf
    state     : present
    backrefs  : yes
    regexp    : '#NameVirtualHost \*:80'
    line      : 'NameVirtualHost *:80'

- name        : VirtualHostを有効にする(SSL)
  notify      : httpd再起動
  template    :
    src       : ssl.conf.j2
    dest      : /etc/httpd/conf.d/ssl.conf

- name        : 仮想マシンにVirtualHostの設定ファイルを作成
  notify      : httpd再起動
  template    :
    src       : local_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_local

- name        : 本番サーバーにVirtualHostの設定ファイルを作成
  notify      : httpd再起動
  template    :
    src       : remote_virtualhost.conf.j2
    dest      : /etc/httpd/conf.d/virtualhost.conf
  when        : target_is_remote
