---
- name          : httpdインストール
  yum           :
    name        : httpd-{{ httpd_version }}
    state       : installed

# - name: Ensure Apache is installed on RHEL.
#   yum:
#     name: "{{ item }}"
#     state: "{{ apache_packages_state }}"
#     enablerepo: "{{ apache_enablerepo }}"
#   with_items: "{{ apache_packages }}"
