---
# PHP
- name: phpのリポジトリのインストール
  yum:
    name: "{{ php_.repo_url }}"
    state: installed

- name          : phpと関連パッケージインストール
  yum           :
    name        : "{{ php_.install_packages }}"
    enablerepo  : "{{ php_.enablerepo }}"
    state       : installed

- name          : /etc/httpd/conf/extra/ ディレクトリを作る
  shell         : "mkdir /etc/httpd/conf/extra/"
  ignore_errors : true

- name: httpd-php.confファイルの配置
  shell: "mv /etc/httpd/conf.d/php.conf /etc/httpd/conf/extra/httpd-php.conf"
  args:
    creates: /etc/httpd/conf/extra/httpd-php.conf

- name: httpd-php.confをhttpd.confから読み込む
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: 'Include conf/extra/httpd-php.conf'

- name          : /etc/php.iniを書き換え
  lineinfile    :
    dest        : /etc/php.ini
    state       : present
    backrefs    : yes
    regexp      : "{{ item.regexp }}"
    line        : "{{ item.line }}"  # see group_vars/all.yml
  with_items    : "{{ php_.config_changes }}"
  notify        : httpd再起動
